config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end
  resources :tags
  root to: "articles#index"
  resources :authors

  resources :author_sessions, only: [:new, :create, :destroy]
  get 'login' => 'author_sessions#new'
  post 'login' => 'author_sessions#create'
  get 'logout' => 'author_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :ownerships, dependent: :destroy
  has_many :authors, through: :ownerships


  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    self.tags.collect {|tag| tag.name}.join(", ")
  end

  def tag_list=(tags_string)
    tags_name = tags_string.split(",").collect {|tag| tag.strip.downcase}.uniq
    new_or_found_tags = tags_name.collect {|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end

end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  has_many :ownerships, dependent: :destroy
  has_many :articles, through: :ownerships
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :article
  belongs_to :author
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  # before_action :require_login, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    @article.authors.push(current_user)
    flash.notice = "Article '#{@article.title}' successfully created!"
    redirect_to article_path(@article)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' Updated!"
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    flash.notice = "Article '#{@article.title}' Deleted!!"
    @article.destroy
    redirect_to articles_path
  end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(articles_path, notice: "Logged out!")
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_authors_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    redirect_to article_path(@comment.article_id)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tagging = Tagging.find_by(tag_id: params[:id])
    @tagging.destroy
    @tag.destroy
    redirect_to tags_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h5>Comment by <%= comment.author_name %></h5>
  <p>Posted <%= distance_of_time_in_words(comment.created_at, Time.now)%> ago</p>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
    <li><% error %></li>
    <% end %>
  </ul>
  <div class="form-group"
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group"
    <%= f.label :body %>
    <%= f.text_area :body, rows: 10, class: "form-control" %>
  </div>
  <div class="form-group"
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, class: "form-control" %>
  </div>
  <% if @article.image.exists? %>
    <%= label_tag "Attached Image" %>
    <div class="article-image">
      <%= image_tag @article.image.url%>
    </div>
  <% end %>
  <div class="form-group"
    <%= f.label :image, "Attach an Image" %>
    <%= f.file_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render partial: "form" %>
<%= link_to "<= Back to articles list", articles_path %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<ul>
  <% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article_path(article), class: "article_title", id: "article_#{article.id}" %>
    <% if logged_in? && article.authors.include?(current_user) %>
      <%= link_to "edit", edit_article_path(article) %>
      <%= link_to "delete", article_path(article), method: :delete %>
    <% end %>
  </li>
  <% end %>
</ul>
<% if logged_in? %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: "articles/form" %>

app/views/articles/show.html.erb
<div class="article">
  <h1><%= @article.title %></h1>

  <div class="article_body">
    <p><%= simple_format(@article.body) %></p>
  </div>


  <% if @article.image.exists? %>
  <div class="article-image">
    <%= image_tag @article.image.url%>
  </div>
  <% end %>


  <div class="article_meta">
    <div class="article_tag">
      Tags:
      <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
      <% end %>
    </div>
    <div class="article_author">
      <%= "Author".pluralize(@article.authors.count)%>:
      <% @article.authors.each do |author| %>
      <%= link_to author.username, author_path(author) %>
      (<%= link_to author.email, author_path(author) %>)
      <% end %>
    </div>
    <div class="article_control">
      <% if logged_in? && @article.authors.include?(current_user) %>
        <%= link_to "delete", article_path(@article), method: :delete %>
        <%= link_to "edit", edit_article_path(@article) %>
      <% end %>
    </div>
  </div>

  <div class="article_comment">
    <h4>Comments (<%= @article.comments.size %>)</h4>
    <%= render partial: "articles/comment", collection: @article.comments %>
    <%= render partial: "comments/form" %>
  </div>

</div>
<%= link_to "<= Back to articles list", articles_path %>

app/views/author_sessions/new.html.erb
<div class="login-box">

  <h1>Login</h1>
  <%= form_tag login_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= text_field_tag :email,"", placeholder: "Your email", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password,"", placeholder: "Your password", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit_tag "Login", class: "btn btn-primary" %>
  </div>
  <% end %>
  <p>Test account:<br>
  Email: <strong>binh@gmail.com</strong> <br>
  Password: <strong>binh</strong></p>
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.username, author_path(author) %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<div class="login-box">
  <h1>New Author</h1>

  <%= render 'form', author: @author %>

  <%= link_to 'Back', authors_path %>
</div>

app/views/authors/show.html.erb
<h1>Author: <%= @author.username %></h1>

<ul>
  <% @author.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h4>Post a Comment</h4>
<%= form_for [@article, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :author_name, "Your name" %>
    <%= f.text_field :author_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "partials/navbar" %>
    <div class="container">
    <% if flash.notice %>
      <div class="flash"><%= flash.notice %></div>
    <% end %>
      <%= yield %>
      <br>
      <div id="logged_status">
        <% if logged_in? %>
          <h6>Logged in as <span class="username"><%= "#{current_user.username}" %></span></h6>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Blogger</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Authors", authors_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <% if logged_in? %>
          <%= link_to "Logout", logout_path, class: "nav-link" %>
        <% else %>
          <%= link_to "Login", login_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/tags/index.html.erb
<h1>All tags</h1>
<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
      <% if logged_in? %>
        <%= link_to "delete", tag_path(tag), method: :delete %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles with tag <%= @tag.name.capitalize %></h1>
<ul>
  <% @tag.articles.each do |article| %>
  <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>
<%= link_to "<= Back to articles list", articles_path %>